FROM node:22-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY packages ./packages

COPY apps/frontend ./apps/frontend
COPY apps/backend ./apps/backend

RUN pnpm install --frozen-lockfile

EXPOSE 5173 8080

CMD sh -c "pnpm dev"
