/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as ProvidersRouteImport } from './app/providers'
import { Route as PostsRouteImport } from './app/posts'
import { Route as AboutRouteImport } from './app/about'
import { Route as IndexRouteImport } from './app/index'
import { Route as TuringMachineIdRouteImport } from './app/turing-machine/$id'

const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TuringMachineIdRoute = TuringMachineIdRouteImport.update({
  id: '/turing-machine/$id',
  path: '/turing-machine/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsRoute
  '/providers': typeof ProvidersRoute
  '/turing-machine/$id': typeof TuringMachineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsRoute
  '/providers': typeof ProvidersRoute
  '/turing-machine/$id': typeof TuringMachineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsRoute
  '/providers': typeof ProvidersRoute
  '/turing-machine/$id': typeof TuringMachineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/posts' | '/providers' | '/turing-machine/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/posts' | '/providers' | '/turing-machine/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/posts'
    | '/providers'
    | '/turing-machine/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PostsRoute: typeof PostsRoute
  ProvidersRoute: typeof ProvidersRoute
  TuringMachineIdRoute: typeof TuringMachineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turing-machine/$id': {
      id: '/turing-machine/$id'
      path: '/turing-machine/$id'
      fullPath: '/turing-machine/$id'
      preLoaderRoute: typeof TuringMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PostsRoute: PostsRoute,
  ProvidersRoute: ProvidersRoute,
  TuringMachineIdRoute: TuringMachineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
